# IMPORT LIBRARIES

In [1]:
pip install pandas

Requirement already satisfied: pandas in c:\users\prash\anaconda3\lib\site-packages (1.3.4)
Requirement already satisfied: python-dateutil>=2.7.3 in c:\users\prash\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.17.3 in c:\users\prash\anaconda3\lib\site-packages (from pandas) (1.20.3)
Requirement already satisfied: pytz>=2017.3 in c:\users\prash\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: six>=1.5 in c:\users\prash\anaconda3\lib\site-packages (from python-dateutil>=2.7.3->pandas) (1.16.0)
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

# LOADING THE DATA

In [3]:
Data=pd.read_csv("Life Expectancy Data.csv")

In [4]:
Data.shape

(2938, 22)

In [5]:
Data

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2933,Zimbabwe,2004,Developing,44.3,723.0,27,4.36,0.000000,68.0,31,...,67.0,7.13,65.0,33.6,454.366654,12777511.0,9.4,9.4,0.407,9.2
2934,Zimbabwe,2003,Developing,44.5,715.0,26,4.06,0.000000,7.0,998,...,7.0,6.52,68.0,36.7,453.351155,12633897.0,9.8,9.9,0.418,9.5
2935,Zimbabwe,2002,Developing,44.8,73.0,25,4.43,0.000000,73.0,304,...,73.0,6.53,71.0,39.8,57.348340,125525.0,1.2,1.3,0.427,10.0
2936,Zimbabwe,2001,Developing,45.3,686.0,25,1.72,0.000000,76.0,529,...,76.0,6.16,75.0,42.1,548.587312,12366165.0,1.6,1.7,0.427,9.8
2937,Zimbabwe,2000,Developing,46.0,665.0,24,1.68,0.000000,79.0,1483,...,78.0,7.10,78.0,43.5,547.358878,12222251.0,11.0,11.2,0.434,9.8

In [6]:
Data[:2]

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0

# MISSING VALUE TREATMENT

In [7]:
Data.isnull().sum()

Country                              0
Year                                 0
Status                               0
Life expectancy                     10
Adult Mortality                     10
infant deaths                        0
Alcohol                            194
percentage expenditure               0
Hepatitis B                        553
Measles                              0
 BMI                                34
under-five deaths                    0
Polio                               19
Total expenditure                  226
Diphtheria                          19
 HIV/AIDS                            0
GDP                                448
Population                         652
 thinness  1-19 years               34
 thinness 5-9 years                 34
Income composition of resources    167
Schooling                          163
dtype: int64

In [8]:
Data.columns

Index(['Country', 'Year', 'Status', 'Life expectancy ', 'Adult Mortality',
       'infant deaths', 'Alcohol', 'percentage expenditure', 'Hepatitis B',
       'Measles ', ' BMI ', 'under-five deaths ', 'Polio', 'Total expenditure',
       'Diphtheria ', ' HIV/AIDS', 'GDP', 'Population',
       ' thinness  1-19 years', ' thinness 5-9 years',
       'Income composition of resources', 'Schooling'],
      dtype='object')

In [9]:
Data.dropna(subset=['Life expectancy '],inplace=True)

In [10]:
Data.shape

(2928, 22)

In [11]:
null_columns=['Alcohol','Hepatitis B',' BMI ', 'Polio', 'Total expenditure','Diphtheria ', 'GDP', 'Population',' thinness  1-19 years', ' thinness 5-9 years','Income composition of resources', 'Schooling']

In [12]:
null_col_data=Data[null_columns]

In [13]:
null_col_data.describe()

,Alcohol,Hepatitis B,BMI,Polio,Total expenditure,Diphtheria,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2735.000000,2375.000000,2896.000000,2909.000000,2702.000000,2909.000000,2485.000000,2.284000e+03,2896.000000,2896.000000,2768.000000,2768.000000
mean,4.614856,80.960842,38.235394,82.548298,5.930163,82.321416,7494.210719,1.276454e+07,4.850622,4.881423,0.627419,11.999639
std,4.050749,25.018337,19.959590,23.416674,2.483273,23.706644,14282.251492,6.103765e+07,4.420829,4.509609,0.210978,3.346440
min,0.010000,1.000000,1.000000,3.000000,0.370000,2.000000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,0.905000,77.000000,19.300000,78.000000,4.260000,78.000000,463.852618,1.966738e+05,1.600000,1.575000,0.493000,10.100000
50%,3.770000,92.000000,43.350000,93.000000,5.750000,93.000000,1764.973870,1.391756e+06,3.300000,3.400000,0.677000,12.300000
75%,7.715000,97.000000,56.100000,97.000000,7.490000,97.000000,5932.899677,7.426746e+06,7.200000,7.200000,0.779250,14.300000
max,17.870000,99.000000,77.600000,99.000000,17.600000,99.000000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [14]:
Data[null_columns]=Data[null_columns].fillna(Data[null_columns].mean())

In [15]:
Data.describe()

,Year,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2928.00000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2.928000e+03,2928.000000,2928.000000,2928.000000,2928.000000
mean,2007.50000,69.224932,164.796448,30.407445,4.614856,740.321185,80.960842,2427.855874,38.235394,42.179303,82.548298,5.930163,82.321416,1.747712,7494.210719,1.276454e+07,4.850622,4.881423,0.627419,11.999639
std,4.61056,9.523867,124.292079,118.114450,3.914923,1990.930605,22.531361,11485.970937,19.850184,160.700547,23.340548,2.385478,23.629576,5.085542,13157.128331,5.390628e+07,4.396597,4.484890,0.205131,3.253691
min,2000.00000,36.300000,1.000000,0.000000,0.010000,0.000000,1.000000,0.000000,1.000000,0.000000,3.000000,0.370000,2.000000,0.100000,1.681350,3.400000e+01,0.100000,0.100000,0.000000,0.000000
25%,2003.75000,63.100000,74.000000,0.000000,1.107500,4.853964,80.960842,0.000000,19.400000,0.000000,78.000000,4.370000,78.000000,0.100000,578.797095,4.181205e+05,1.600000,1.600000,0.504000,10.300000
50%,2007.50000,72.100000,144.000000,3.000000,4.160000,65.611455,87.000000,17.000000,43.000000,4.000000,93.000000,5.930163,93.000000,0.100000,3112.560501,3.640009e+06,3.400000,3.400000,0.662000,12.100000
75%,2011.25000,75.700000,228.000000,22.000000,7.400000,442.614322,96.000000,362.250000,56.100000,28.000000,97.000000,7.330000,97.000000,0.800000,7494.210719,1.276454e+07,7.100000,7.200000,0.773000,14.100000
max,2015.00000,89.000000,723.000000,1800.000000,17.870000,19479.911610,99.000000,212183.000000,77.600000,2500.000000,99.000000,17.600000,99.000000,50.600000,119172.741800,1.293859e+09,27.700000,28.600000,0.948000,20.700000

In [16]:
Data.dtypes

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
 HIV/AIDS                          float64
GDP                                float64
Population                         float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Schooling                          float64
dtype: object

In [17]:
num_columns=['Adult Mortality', 'infant deaths',
       'Alcohol', 'percentage expenditure', 'Hepatitis B', 'Measles ', ' BMI ',
       'under-five deaths ', 'Polio', 'Total expenditure', 'Diphtheria ',
       ' HIV/AIDS', 'GDP', 'Population', ' thinness  1-19 years',
       ' thinness 5-9 years', 'Income composition of resources', 'Schooling']

In [18]:
cat_columns=['Country','Status']

In [19]:
num_data=Data[num_columns]

In [20]:
cat_data=Data[cat_columns]

# TREATING OUTLIERS

In [21]:
for col in num_data:

    q1=np.percentile(num_data[col],25) 
    q3=np.percentile(num_data[col],75)

    IQR=q3-q1
    
    print('Outliers for :',col,'\n')
  
    upper=q3+1.5*IQR

    lower=q1-1.5*IQR
   
    outliers=[]
    
    for i in num_data[col]:
        if(i<lower or i>upper):
            outliers.append(i)
    print("Outliers are:",outliers)
    print("\n")

Outliers for : Adult Mortality

Outliers are: [491.0, 566.0, 652.0, 693.0, 699.0, 679.0, 647.0, 466.0, 472.0, 473.0, 473.0, 467.0, 461.0, 477.0, 495.0, 511.0, 512.0, 593.0, 682.0, 484.0, 522.0, 518.0, 513.0, 527.0, 566.0, 592.0, 633.0, 654.0, 675.0, 666.0, 648.0, 622.0, 586.0, 543.0, 462.0, 491.0, 525.0, 559.0, 587.0, 615.0, 613.0, 599.0, 588.0, 477.0, 483.0, 471.0, 463.0, 464.0, 496.0, 513.0, 519.0, 533.0, 473.0, 486.0, 496.0, 498.0, 497.0, 485.0, 477.0, 564.0, 587.0, 568.0, 536.0, 485.0, 523.0, 539.0, 554.0, 487.0, 526.0, 554.0, 578.0, 611.0, 614.0, 464.0, 527.0, 587.0, 632.0, 717.0, 723.0, 715.0, 686.0, 665.0]


Outliers for : infant deaths

Outliers are: [62, 64, 66, 69, 71, 74, 77, 80, 82, 84, 85, 87, 87, 88, 88, 88, 66, 67, 69, 72, 75, 78, 81, 84, 87, 90, 92, 94, 95, 96, 97, 97, 92, 98, 104, 111, 118, 126, 135, 144, 154, 164, 174, 185, 196, 207, 219, 231, 57, 61, 65, 70, 75, 81, 88, 95, 103, 111, 57, 58, 59, 59, 60, 60, 60, 60, 61, 62, 63, 64, 64, 65, 65, 67, 56, 57, 58, 58, 59, 60, 60, 61, 62, 157, 171, 185, 201, 215, 231, 248, 266, 285, 307, 332, 360, 391, 422, 457, 490, 236, 237, 238, 239, 239, 239, 238, 237, 236, 235, 233, 232, 231, 229, 227, 226, 56, 57, 59, 61, 63, 65, 136, 140, 145, 150, 156, 162, 169, 177, 186, 196, 206, 217, 228, 237, 246, 253, 910, 957, 1000, 1100, 1100, 1200, 1300, 1300, 1400, 1500, 1500, 1600, 1700, 1700, 1800, 1800, 114, 119, 124, 129, 134, 138, 143, 149, 154, 159, 163, 174, 173, 177, 182, 187, 56, 58, 59, 60, 61, 62, 64, 66, 68, 70, 72, 74, 76, 77, 77, 56, 57, 57, 58, 59, 60, 60, 60, 60, 61, 62, 64, 66, 69, 70, 72, 74, 78, 80, 82, 85, 87, 90, 93, 59, 58, 61, 64, 66, 69, 71, 72, 73, 56, 56, 57, 57, 58, 483, 490, 498, 505, 513, 521, 527, 536, 542, 549, 556, 563, 567, 571, 574, 576, 352, 359, 365, 369, 371, 372, 371, 369, 367, 365, 364, 364, 366, 371, 377, 385, 56, 57, 58, 59, 60, 62, 63, 65, 66, 67, 68, 68, 69, 58, 59, 60, 61, 61, 62, 63, 64, 65, 66, 66, 68, 69, 70, 71, 71, 66, 68, 71, 73, 76, 79, 82, 84, 88, 93, 99, 104, 109, 112, 115, 116, 85, 86, 86, 87, 88, 89, 91, 92, 94, 96, 97, 100, 103, 106, 110, 114]


Outliers for : Alcohol

Outliers are: [17.31, 16.99, 17.87]


Outliers for : percentage expenditure

Outliers are: [2422.999774, 1991.430372, 2156.229842, 1810.875316, 1983.956937, 1455.608186, 1158.065259, 1127.74347, 1133.558003, 1504.329462, 1398.042623, 1413.73543, 1105.659031, 1349.025282, 10769.36305, 11734.85381, 11714.99858, 10986.26527, 8875.786493, 7172.275229, 8547.292357, 6187.062017, 3829.550928, 3064.301144, 8350.193523, 7878.372355, 8272.306757, 7423.228774, 8053.557638, 8329.731655, 7453.8644, 5992.588029, 5316.877456, 3979.057728, 3582.848308, 3557.455507, 2211.215778, 1553.468944, 1380.228095, 1214.558167, 1150.418063, 1641.30981, 1311.440423, 1140.615754, 1147.1114, 1109.854619, 7163.348923, 7191.051507, 5579.199083, 5068.214488, 5160.508378, 2943.375396, 1111.191325, 2845.306444, 3192.634413, 2218.364226, 1873.686852, 2538.941033, 2048.557422, 1504.30004, 1406.51194, 9733.228019, 9748.636237, 8649.674911, 8433.936814, 7946.743581, 6333.177967, 5513.329924, 4687.845565, 3895.856308, 3665.089703, 3787.49456, 2352.999591, 2442.222054, 2260.777642, 1275.689625, 1435.487755, 1487.896562, 2568.237059, 2429.854745, 2377.010299, 1859.095621, 1185.412346, 1884.098811, 1899.107385, 1851.713262, 1913.356642, 2160.380199, 2425.403891, 2019.812779, 1555.651986, 1116.396502, 2159.756205, 2443.325028, 1958.525877, 1700.841534, 1562.520827, 1586.724172, 1128.050886, 10468.76292, 10261.763, 10251.10872, 9765.616994, 10761.18209, 9703.068121, 7627.412444, 6948.839868, 4801.546125, 1500.412635, 1493.051277, 1192.696619, 1705.678619, 2700.07305, 2263.103797, 2146.945741, 1802.017593, 1717.088711, 1904.12469, 6164.455402, 6115.496624, 5889.012536, 6147.1323, 4816.589613, 4508.806185, 3869.026302, 3099.357319, 2775.33544, 6739.677606, 6646.953935, 6415.35735, 7002.785925, 5689.991931, 5451.701225, 5291.234786, 4572.441963, 3779.655273, 3451.185079, 3410.284431, 7584.078579, 7641.270645, 8285.264655, 7777.556353, 6407.535954, 6012.92584, 5842.374765, 4057.637383, 4238.540035, 2163.043414, 2183.106986, 2528.992935, 3192.887363, 3189.754439, 3682.88717, 3632.243121, 2785.139364, 2124.921517, 1403.022211, 1281.155944, 1299.459306, 1317.08348, 8254.020763, 6818.546407, 6005.575763, 7613.814999, 12042.97366, 10631.20379, 8506.101443, 5948.096777, 5048.274426, 5809.12199, 6616.695125, 6386.95437, 4509.234803, 7620.823456, 9528.230574, 9797.552661, 9126.931178, 8040.220444, 5092.383814, 4264.579203, 3794.581463, 4348.33531, 4279.895512, 3830.184587, 3793.161624, 1895.342792, 1731.755747, 1701.195787, 4831.644796, 4793.904924, 5439.691769, 5219.668802, 5243.316638, 5228.821581, 4506.255963, 4270.914882, 3519.258515, 2883.334911, 9498.729062, 7313.175418, 6599.995239, 6502.136974, 6799.664423, 6746.281299, 5250.249188, 5486.51208, 5926.296654, 2480.896965, 2792.677582, 2957.973963, 2785.097712, 2009.575605, 3001.628237, 2078.392748, 2555.303869, 2443.444275, 1731.073528, 1209.680547, 1542.635979, 1356.022164, 1109.969508, 1137.6237, 2211.744178, 1968.816817, 1807.071336, 1758.822757, 1423.802386, 1446.529217, 1888.149904, 1581.511914, 16255.16198, 15515.75234, 2284.58215, 17028.52798, 2267.252192, 2052.393076, 18961.3486, 15345.4907, 1346.246697, 12372.05188, 10111.38928, 7877.33656, 8246.130437, 2051.748615, 1626.591186, 1259.940376, 3601.287457, 2655.573684, 2578.888314, 2380.699796, 2247.035692, 1678.392773, 1552.740429, 1117.196097, 1491.703605, 1475.030397, 1162.656768, 10873.40554, 9689.732784, 8344.010392, 6577.508136, 5170.130703, 4472.6114, 3455.197053, 3054.515582, 2944.640134, 10019.0763, 8342.405764, 6664.148708, 6761.288966, 3661.792922, 2892.257132, 2205.98595, 2143.021083, 2094.19096, 15268.06445, 1707.130633, 14829.41215, 12829.25408, 11792.53465, 6356.827282, 6191.211908, 1154.893473, 1842.463782, 1694.467075, 1199.319976, 1299.159757, 2698.01817, 3108.288623, 3119.349824, 3652.869332, 2884.020194, 2813.985285, 2283.891796, 1904.00231, 1657.328352, 5063.513104, 5163.32918, 4409.17067, 3688.694288, 5484.143308, 4582.476081, 4064.743869, 4049.972347, 1559.287158, 1230.748231, 1340.553699, 1529.497771, 2017.643131, 2047.113102, 1197.946328, 1307.89002, 1395.454965, 1117.048134, 1521.672751, 1121.475547, 7971.646361, 6041.858981, 4540.543752, 3404.13099, 3082.973535, 2639.376955, 2356.731479, 2263.068326, 1855.828806, 3283.024864, 3343.026219, 3187.496219, 3505.389434, 3256.724028, 2724.17807, 2503.714258, 1617.473418, 4255.781693, 4873.8188, 5047.254058, 5596.535203, 4460.390006, 3715.370095, 3205.019918, 2044.169761, 1934.398154, 1132.432517, 1122.972967, 1168.324095, 1142.212403, 1212.666327, 10947.02327, 11477.6671, 8105.590882, 7593.391622, 6369.516139, 5793.363644, 5067.411418, 3998.09987, 3554.546434, 3689.7273, 19479.91161, 19099.04506, 18379.32974, 18822.86732, 2198.590865, 14714.82588, 2084.255535, 11892.33429, 10598.08187, 10055.34981, 9495.540576, 6853.628494, 6478.346135, 5834.582046, 1578.872339, 1486.236406, 1389.772683, 1902.693048, 1187.949491, 1275.877569, 3862.68271, 3663.764502, 4003.908598, 3759.457226, 3749.941617, 3427.320332, 2972.448675, 2598.842827, 2331.532804, 1871.736563, 1712.225506]


Outliers for : Hepatitis B

Outliers are: [9.0, 8.0, 9.0, 55.0, 44.0, 33.0, 8.0, 52.0, 49.0, 5.0, 51.0, 5.0, 9.0, 21.0, 45.0, 11.0, 5.0, 18.0, 56.0, 7.0, 6.0, 6.0, 6.0, 8.0, 7.0, 15.0, 8.0, 9.0, 9.0, 36.0, 9.0, 9.0, 8.0, 48.0, 1.0, 9.0, 4.0, 8.0, 8.0, 55.0, 55.0, 55.0, 7.0, 7.0, 56.0, 42.0, 28.0, 14.0, 14.0, 14.0, 14.0, 14.0, 47.0, 47.0, 23.0, 47.0, 47.0, 45.0, 42.0, 46.0, 37.0, 39.0, 4.0, 33.0, 39.0, 24.0, 17.0, 9.0, 9.0, 7.0, 6.0, 9.0, 8.0, 28.0, 8.0, 9.0, 7.0, 9.0, 8.0, 27.0, 8.0, 6.0, 7.0, 25.0, 8.0, 8.0, 8.0, 9.0, 36.0, 9.0, 16.0, 2.0, 9.0, 9.0, 56.0, 52.0, 47.0, 51.0, 47.0, 42.0, 39.0, 35.0, 35.0, 28.0, 29.0, 28.0, 26.0, 8.0, 7.0, 52.0, 28.0, 54.0, 48.0, 51.0, 55.0, 9.0, 9.0, 9.0, 8.0, 8.0, 8.0, 9.0, 54.0, 51.0, 57.0, 57.0, 57.0, 8.0, 9.0, 6.0, 48.0, 7.0, 44.0, 38.0, 37.0, 29.0, 6.0, 6.0, 8.0, 6.0, 56.0, 56.0, 46.0, 9.0, 36.0, 9.0, 8.0, 5.0, 9.0, 9.0, 57.0, 44.0, 5.0, 57.0, 49.0, 45.0, 5.0, 9.0, 8.0, 8.0, 9.0, 6.0, 17.0, 52.0, 5.0, 8.0, 47.0, 7.0, 7.0, 51.0, 9.0, 9.0, 8.0, 8.0, 42.0, 9.0, 8.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 43.0, 8.0, 25.0, 58.0, 4.0, 39.0, 8.0, 9.0, 41.0, 27.0, 2.0, 51.0, 2.0, 2.0, 9.0, 9.0, 9.0, 9.0, 7.0, 49.0, 49.0, 46.0, 42.0, 46.0, 49.0, 41.0, 42.0, 27.0, 18.0, 7.0, 8.0, 8.0, 56.0, 6.0, 6.0, 57.0, 9.0, 9.0, 6.0, 49.0, 48.0, 52.0, 42.0, 45.0, 7.0, 7.0, 58.0, 9.0, 43.0, 14.0, 31.0, 56.0, 6.0, 58.0, 57.0, 44.0, 12.0, 46.0, 35.0, 41.0, 54.0, 7.0, 43.0, 54.0, 9.0, 9.0, 42.0, 42.0, 42.0, 8.0, 7.0, 31.0, 32.0, 6.0, 22.0, 9.0, 9.0, 9.0, 53.0, 42.0, 41.0, 47.0, 43.0, 8.0, 8.0, 58.0, 39.0, 9.0, 53.0, 24.0, 8.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 5.0, 8.0, 44.0, 29.0, 22.0, 22.0, 46.0, 46.0, 21.0, 48.0, 48.0, 7.0, 4.0, 9.0, 9.0, 9.0, 9.0, 9.0, 6.0, 7.0, 53.0, 6.0, 53.0, 5.0, 8.0, 43.0, 38.0, 31.0, 19.0, 14.0, 9.0, 8.0, 9.0, 7.0]


Outliers for : Measles

Outliers are: [1154, 2787, 3013, 1989, 2861, 1599, 1141, 1990, 1296, 2486, 8762, 6532, 944, 2302, 3289, 15374, 5862, 2686, 11699, 8523, 4458, 1449, 1190, 2807, 1014, 1196, 11945, 9046, 2219, 2281, 1783, 1238, 1978, 4353, 1986, 5625, 2660, 2924, 6192, 25934, 9743, 4067, 3484, 4414, 5098, 1461, 928, 1588, 5859, 4244, 1677, 3000, 2672, 22004, 2249, 7362, 2511, 54118, 2946, 1744, 4174, 6074, 1016, 18363, 3466, 4770, 5882, 5790, 5729, 1156, 4779, 4211, 1361, 3761, 12237, 1809, 1448, 23934, 14629, 1233, 938, 2837, 3207, 1275, 8650, 1594, 10324, 15801, 7277, 24908, 3546, 42361, 52628, 26883, 6183, 9943, 38159, 52461, 131441, 109023, 99602, 124219, 70549, 71879, 58341, 88962, 71093, 912, 1359, 3524, 3712, 2788, 2152, 1678, 3550, 5020, 33711, 88381, 72029, 133802, 5407, 12461, 55577, 80123, 182485, 44934, 21956, 30466, 8072, 8282, 5432, 1314, 1684, 953, 2150, 2633, 1250, 1190, 1339, 17745, 12739, 5253, 4347, 3255, 4235, 1176, 3511, 1446, 1451, 3332, 2366, 1660, 14949, 5048, 1541, 4448, 5185, 10000, 5129, 3188, 7872, 1356, 6847, 2464, 1771, 1607, 917, 2307, 4657, 6024, 1613, 1939, 12289, 13476, 23068, 2497, 2151, 7408, 11294, 3526, 1158, 992, 90387, 79563, 13822, 18668, 33634, 31458, 56188, 44258, 41144, 64185, 36711, 55443, 47147, 40044, 51780, 38835, 15099, 12943, 8419, 15489, 21893, 18869, 20818, 15369, 19456, 20422, 15853, 29171, 24457, 14492, 3825, 3344, 11644, 9554, 9582, 11874, 1433, 1317, 30328, 5494, 908, 9081, 4088, 931, 5189, 1617, 10982, 9385, 1457, 11015, 8752, 8286, 33812, 22552, 22497, 16118, 2204, 2395, 1218, 1282, 1516, 1847, 11304, 21002, 17779, 1678, 1491, 1810, 2070, 1761, 956, 2488, 1060, 2200, 1379, 5977, 2771, 3890, 35558, 62233, 10795, 9357, 35256, 118712, 1116, 1318, 1868, 1569, 1407, 5729, 2198, 6187, 1395, 926, 1719, 2939, 4464, 1578, 1292, 5039, 3611, 1398, 20359, 1205, 10677, 925, 982, 1455, 2248, 1217, 6399, 10841, 6000, 2724, 7368, 2321, 12598, 9396, 28898, 7155, 7085, 7375, 1010, 2175, 2046, 1088, 1329, 2519, 1028, 3138, 4076, 1278, 1599, 1279, 1861, 3362, 2359, 2089, 1415, 2838, 5023, 12074, 13344, 6749, 10849, 9397, 2632, 1019, 7693, 1142, 1224, 1317, 2183, 63057, 54190, 31584, 61208, 21319, 12423, 6855, 52852, 6447, 18843, 8491, 1272, 9960, 2613, 110927, 31521, 141258, 42007, 168107, 212183, 1370, 8749, 8046, 4386, 4321, 1129, 2801, 7641, 2981, 4248, 4740, 3903, 3849, 2064, 2299, 1222, 1385, 3863, 17620, 4023, 7135, 58848, 2920, 1536, 6538, 6368, 1469, 3025, 10511, 7003, 7360, 7120, 23060, 32647, 4929, 1159, 7450, 4189, 3196, 5043, 4711, 2339, 2123, 1147, 2444, 3291, 2072, 4800, 1064, 2738, 2095, 1164, 4648, 1880, 1208, 999, 1519, 18184, 24789, 5839, 1006, 1865, 1089, 3575, 7497, 10229, 3173, 9983, 17298, 1081, 1149, 12008, 8257, 9559, 3571, 3965, 12499, 5857, 1043, 1166, 1459, 1952, 1256, 1204, 3802, 1568, 1686, 2107, 16527, 3585, 2813, 8523, 5616, 1374, 9562, 4381, 4529, 4362, 2875, 958, 2022, 1015, 2144, 927, 2641, 5197, 3156, 2583, 6071, 7790, 3893, 3588, 3526, 4165, 4519, 10315, 7319, 4074, 1833, 3578, 7405, 6200, 8927, 5844, 7823, 30509, 16244, 7878, 2027, 3312, 1313, 1601, 1319, 3776, 5736, 29429, 49871, 48543, 42554, 12746, 1333, 1005, 42724, 2392, 7587, 16970, 1919, 2092, 1112, 1212, 1445, 1022, 1668, 1622, 1574, 3413, 7726, 2362, 1419, 1673, 5131, 11847, 14649, 2392, 15033, 1123, 2809, 6582, 1978, 2297, 6755, 12058, 16512, 2177, 2676, 8079, 6285, 12708, 8536, 13234, 15754, 25036, 16997, 30930, 9696, 998, 1483]


Outliers for :  BMI

Outliers are: []


Outliers for : under-five deaths

Outliers are: [83, 86, 89, 93, 97, 102, 106, 110, 113, 116, 118, 120, 122, 122, 122, 122, 98, 101, 105, 110, 115, 121, 127, 133, 138, 143, 148, 152, 155, 157, 159, 160, 113, 121, 130, 139, 150, 161, 173, 186, 201, 215, 231, 247, 264, 280, 298, 316, 73, 79, 85, 93, 100, 109, 118, 127, 71, 74, 77, 80, 83, 86, 89, 91, 92, 93, 93, 92, 79, 80, 81, 82, 83, 84, 84, 85, 87, 89, 90, 91, 92, 93, 94, 95, 71, 73, 76, 79, 82, 85, 87, 89, 91, 93, 94, 95, 97, 99, 100, 77, 78, 78, 79, 79, 80, 80, 80, 80, 80, 79, 78, 77, 76, 75, 74, 183, 198, 216, 233, 251, 268, 288, 308, 332, 360, 392, 427, 467, 511, 558, 608, 308, 312, 314, 317, 319, 321, 323, 324, 326, 327, 329, 330, 331, 331, 332, 332, 72, 75, 78, 82, 194, 202, 211, 221, 231, 243, 256, 270, 286, 304, 323, 342, 360, 377, 392, 404, 1100, 1200, 1300, 1400, 1500, 1600, 1700, 1800, 1900, 2000, 2000, 2100, 2200, 2300, 2400, 2500, 136, 142, 148, 154, 161, 167, 174, 181, 188, 194, 201, 237, 215, 222, 229, 237, 75, 79, 81, 84, 86, 89, 91, 95, 100, 104, 108, 112, 115, 118, 120, 121, 75, 80, 84, 84, 85, 86, 88, 90, 91, 93, 94, 96, 98, 101, 103, 106, 108, 110, 111, 81, 84, 87, 90, 94, 98, 101, 104, 108, 113, 117, 120, 124, 127, 132, 136, 96, 78, 83, 87, 90, 93, 96, 98, 100, 87, 88, 89, 90, 93, 95, 99, 102, 106, 110, 114, 118, 121, 124, 127, 128, 747, 759, 773, 788, 802, 817, 832, 848, 863, 879, 893, 907, 918, 928, 936, 943, 433, 442, 450, 456, 459, 461, 460, 460, 459, 458, 459, 461, 466, 474, 483, 495, 71, 72, 74, 76, 78, 80, 82, 84, 86, 87, 89, 89, 90, 80, 80, 81, 82, 82, 83, 84, 84, 84, 83, 82, 80, 78, 77, 75, 74, 75, 79, 82, 84, 83, 82, 79, 76, 73, 85, 86, 88, 89, 91, 92, 94, 95, 97, 99, 101, 102, 104, 106, 108, 109, 93, 97, 103, 109, 114, 119, 124, 130, 137, 145, 155, 164, 173, 181, 187, 191, 119, 121, 124, 126, 128, 131, 135, 138, 141, 145, 149, 154, 160, 166, 173, 181, 72]


Outliers for : Polio

Outliers are: [6.0, 5.0, 41.0, 36.0, 35.0, 24.0, 7.0, 36.0, 39.0, 4.0, 4.0, 37.0, 41.0, 3.0, 9.0, 9.0, 8.0, 8.0, 9.0, 9.0, 9.0, 9.0, 8.0, 8.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 45.0, 7.0, 7.0, 9.0, 9.0, 8.0, 8.0, 9.0, 47.0, 47.0, 23.0, 47.0, 47.0, 46.0, 45.0, 46.0, 46.0, 47.0, 47.0, 45.0, 44.0, 42.0, 4.0, 38.0, 44.0, 46.0, 4.0, 43.0, 32.0, 3.0, 38.0, 49.0, 37.0, 31.0, 36.0, 31.0, 26.0, 3.0, 9.0, 9.0, 9.0, 8.0, 7.0, 7.0, 8.0, 9.0, 5.0, 41.0, 32.0, 31.0, 9.0, 8.0, 9.0, 8.0, 6.0, 47.0, 4.0, 3.0, 42.0, 9.0, 49.0, 46.0, 9.0, 9.0, 9.0, 9.0, 9.0, 17.0, 24.0, 3.0, 3.0, 39.0, 5.0, 48.0, 46.0, 44.0, 43.0, 41.0, 9.0, 7.0, 7.0, 7.0, 8.0, 44.0, 44.0, 44.0, 44.0, 44.0, 44.0, 44.0, 9.0, 8.0, 8.0, 9.0, 9.0, 9.0, 8.0, 42.0, 42.0, 6.0, 46.0, 47.0, 9.0, 6.0, 5.0, 9.0, 8.0, 8.0, 8.0, 8.0, 7.0, 7.0, 8.0, 8.0, 9.0, 9.0, 9.0, 7.0, 8.0, 8.0, 9.0, 6.0, 46.0, 5.0, 46.0, 8.0, 9.0, 9.0, 9.0, 9.0, 49.0, 8.0, 47.0, 49.0, 9.0, 7.0, 8.0, 6.0, 7.0, 7.0, 8.0, 8.0, 9.0, 8.0, 9.0, 9.0, 9.0, 8.0, 9.0, 9.0, 8.0, 8.0, 4.0, 46.0, 45.0, 44.0, 43.0, 42.0, 41.0, 49.0, 49.0, 46.0, 42.0, 48.0, 6.0, 46.0, 45.0, 43.0, 42.0, 4.0, 36.0, 31.0, 7.0, 7.0, 8.0, 8.0, 8.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 7.0, 6.0, 45.0, 49.0, 37.0, 26.0, 9.0, 6.0, 49.0, 49.0, 38.0, 46.0, 9.0, 47.0, 47.0, 47.0, 47.0, 49.0, 49.0, 41.0, 4.0, 4.0, 26.0, 35.0, 3.0, 4.0, 4.0, 33.0, 37.0, 7.0, 7.0, 41.0, 44.0, 5.0, 9.0, 6.0, 7.0, 5.0, 5.0, 47.0, 6.0, 7.0, 38.0, 8.0, 8.0, 8.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 7.0, 45.0, 9.0, 9.0, 9.0, 8.0, 8.0, 9.0, 7.0, 8.0, 9.0, 7.0]


Outliers for : Total expenditure

Outliers are: [11.78, 11.8, 12.24, 12.23, 13.66, 11.79, 11.87, 14.39, 11.83, 12.6, 13.73, 13.71, 13.38, 12.77, 13.76, 13.83, 13.44, 12.94, 11.99, 11.92, 12.11, 11.87, 12.8, 12.49, 11.9, 11.98, 13.13, 12.25, 11.96, 11.83, 13.63, 11.93, 11.97, 11.8, 17.14, 16.9, 17.2, 17.6, 17.2, 17.0, 16.2, 15.57, 15.27, 15.15, 15.14, 15.6, 14.55, 13.73, 13.7]


Outliers for : Diphtheria

Outliers are: [5.0, 41.0, 36.0, 33.0, 24.0, 6.0, 34.0, 38.0, 4.0, 4.0, 41.0, 38.0, 28.0, 9.0, 9.0, 5.0, 8.0, 7.0, 9.0, 8.0, 9.0, 45.0, 8.0, 8.0, 9.0, 9.0, 9.0, 8.0, 6.0, 8.0, 8.0, 47.0, 47.0, 23.0, 47.0, 47.0, 45.0, 42.0, 45.0, 48.0, 47.0, 44.0, 4.0, 37.0, 46.0, 37.0, 39.0, 4.0, 33.0, 39.0, 24.0, 19.0, 28.0, 4.0, 25.0, 21.0, 23.0, 25.0, 26.0, 36.0, 9.0, 9.0, 8.0, 8.0, 7.0, 7.0, 8.0, 9.0, 5.0, 41.0, 31.0, 33.0, 9.0, 9.0, 8.0, 6.0, 7.0, 6.0, 41.0, 38.0, 3.0, 4.0, 9.0, 46.0, 9.0, 16.0, 2.0, 3.0, 24.0, 41.0, 44.0, 43.0, 42.0, 41.0, 4.0, 39.0, 38.0, 37.0, 36.0, 35.0, 34.0, 9.0, 9.0, 5.0, 46.0, 44.0, 4.0, 37.0, 35.0, 32.0, 3.0, 9.0, 8.0, 7.0, 45.0, 45.0, 45.0, 45.0, 45.0, 45.0, 45.0, 8.0, 8.0, 9.0, 9.0, 8.0, 8.0, 6.0, 6.0, 5.0, 46.0, 8.0, 6.0, 49.0, 9.0, 6.0, 48.0, 6.0, 6.0, 48.0, 45.0, 41.0, 9.0, 7.0, 7.0, 8.0, 9.0, 9.0, 9.0, 9.0, 8.0, 8.0, 7.0, 9.0, 5.0, 49.0, 45.0, 49.0, 8.0, 8.0, 9.0, 9.0, 5.0, 8.0, 7.0, 6.0, 6.0, 31.0, 35.0, 39.0, 42.0, 46.0, 7.0, 7.0, 6.0, 9.0, 49.0, 43.0, 8.0, 8.0, 7.0, 9.0, 8.0, 8.0, 7.0, 9.0, 9.0, 9.0, 8.0, 9.0, 9.0, 9.0, 9.0, 7.0, 45.0, 43.0, 41.0, 39.0, 36.0, 34.0, 49.0, 49.0, 46.0, 42.0, 48.0, 42.0, 4.0, 36.0, 33.0, 29.0, 25.0, 27.0, 29.0, 9.0, 8.0, 8.0, 9.0, 9.0, 6.0, 8.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 7.0, 49.0, 26.0, 39.0, 49.0, 6.0, 38.0, 44.0, 9.0, 9.0, 9.0, 42.0, 42.0, 42.0, 42.0, 41.0, 45.0, 42.0, 31.0, 4.0, 26.0, 35.0, 3.0, 4.0, 4.0, 33.0, 33.0, 7.0, 31.0, 39.0, 45.0, 9.0, 6.0, 9.0, 41.0, 43.0, 41.0, 45.0, 8.0, 8.0, 8.0, 8.0, 8.0, 7.0, 5.0, 8.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 9.0, 8.0, 23.0, 23.0, 5.0, 9.0, 9.0, 9.0, 9.0, 9.0, 7.0, 7.0, 5.0, 7.0, 9.0, 8.0, 7.0]


Outliers for :  HIV/AIDS


In [22]:
for col in num_data:
    tenth_percentile=np.percentile(num_data[col],10)
    ninetieth_percentile=np.percentile(num_data[col],90)
    print(tenth_percentile,ninetieth_percentile)
    num_data[col]=np.where(num_data[col]<tenth_percentile,tenth_percentile,num_data[col]) 
    num_data[col]=np.where(num_data[col]>ninetieth_percentile,ninetieth_percentile,num_data[col])

19.0 336.0
0.0 58.0
0.03 10.62
0.0 1856.8088505000005
55.0 98.0
0.0 3585.9000000000005
12.169999999999998 61.7
0.0 87.0
52.0 99.0
2.937 8.9
49.0 99.0
0.1 4.4
196.49262484 18833.563776000028
47527.299999999996 18307244.900000006
0.8 9.7
0.8 9.7
0.3937 0.86
7.869999999999999 15.9

In [23]:
num_data.describe()

,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
count,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2928.000000,2.928000e+03,2928.000000,2928.000000,2928.000000,2928.000000
mean,155.890369,13.996585,4.467803,370.704896,84.208110,588.633094,38.577815,20.073087,85.521659,5.863015,85.175583,0.881523,5258.396494,6.632154e+06,4.371865,4.385931,0.644497,12.110674
std,100.421557,19.814807,3.622890,589.091376,13.437590,1152.786581,18.175055,29.620227,15.265170,1.881153,15.894823,1.434869,5827.402863,6.584042e+06,3.107212,3.112742,0.153190,2.530896
min,19.000000,0.000000,0.030000,0.000000,55.000000,0.000000,12.170000,0.000000,52.000000,2.937000,49.000000,0.100000,196.492625,4.752730e+04,0.800000,0.800000,0.393700,7.870000
25%,74.000000,0.000000,1.107500,4.853964,80.960842,0.000000,19.400000,0.000000,78.000000,4.370000,78.000000,0.100000,578.797095,4.181205e+05,1.600000,1.600000,0.504000,10.300000
50%,144.000000,3.000000,4.160000,65.611455,87.000000,17.000000,43.000000,4.000000,93.000000,5.930163,93.000000,0.100000,3112.560501,3.640009e+06,3.400000,3.400000,0.662000,12.100000
75%,228.000000,22.000000,7.400000,442.614322,96.000000,362.250000,56.100000,28.000000,97.000000,7.330000,97.000000,0.800000,7494.210719,1.276454e+07,7.100000,7.200000,0.773000,14.100000
max,336.000000,58.000000,10.620000,1856.808851,98.000000,3585.900000,61.700000,87.000000,99.000000,8.900000,99.000000,4.400000,18833.563776,1.830724e+07,9.700000,9.700000,0.860000,15.900000

# ENCODING THE CATEGORICAL DATA

In [24]:
cat_data

          Country      Status
0     Afghanistan  Developing
1     Afghanistan  Developing
2     Afghanistan  Developing
3     Afghanistan  Developing
4     Afghanistan  Developing
...           ...         ...
2933     Zimbabwe  Developing
2934     Zimbabwe  Developing
2935     Zimbabwe  Developing
2936     Zimbabwe  Developing
2937     Zimbabwe  Developing

[2928 rows x 2 columns]

In [25]:
cat_data['Country'].value_counts()

Afghanistan    16
New Zealand    16
Niger          16
Nigeria        16
Norway         16
               ..
Ghana          16
Greece         16
Grenada        16
Guatemala      16
Zimbabwe       16
Name: Country, Length: 183, dtype: int64

In [26]:
cat_data.nunique()

Country    183
Status       2
dtype: int64

In [27]:
cat_data=cat_data.drop('Country',axis=1)

In [28]:
cat_data['Status'].value_counts()

Developing    2416
Developed      512
Name: Status, dtype: int64

In [29]:
cat_data=cat_data.replace({'Status':{'Developing':0,'Developed':1}})

In [30]:
data=pd.concat([Data['Year'],num_data,cat_data,Data['Life expectancy ']],axis=1)

# TRAIN-TEST SPLIT

In [31]:
x=data.drop('Life expectancy ',axis=1)
y=data['Life expectancy ']

In [32]:
def train_test_split(Data, test_ratio):
    
    Data=Data.sample(frac=1,random_state=42)

    samples=int(len(Data)*(1-test_ratio))

    train_data=Data[:samples]
    test_data=Data[samples:]

    return train_data, test_data

In [33]:
train_data, test_data = train_test_split(data, 0.3)

In [34]:
X_train,Y_train=train_data.iloc[:,:-1].values, train_data.iloc[:,-1].values.reshape(-1,1)

In [35]:
X_test,Y_test=test_data.iloc[:,:-1].values, test_data.iloc[:,-1].values.reshape(-1,1)

In [36]:
Y_test.shape

(879, 1)

In [37]:
param_grid = {
    'max_depth': range(2,50,1),
    'min_samples_split': range(1,20,1),
    'min_samples_leaf': range(1,15,1)
}

# NODE CLASS

In [38]:
class Node():
    def __init__(self, feature_index=None, threshold=None, left=None, right=None, var_red=None, value=None):
        ''' constructor ''' 
        
        # for decision node
        self.feature_index = feature_index
        self.threshold = threshold
        self.left = left
        self.right = right
        self.var_red = var_red
        
        # for leaf node
        self.value = value

# TREE CLASS

In [39]:
class DecisionTreeRegressor():
    def __init__(self, min_samples_split=2, max_depth=2):
        ''' constructor '''
        
        # initialize the root of the tree 
        self.root = None
        
        # stopping conditions
        self.min_samples_split = min_samples_split
        self.max_depth = max_depth
        
    def build_tree(self, dataset, curr_depth=0):
        ''' recursive function to build the tree '''
        
        X, Y = dataset[:,:-1], dataset[:,-1]
        num_samples, num_features = np.shape(X)
        best_split = {}
        # split until stopping conditions are met
        if num_samples>=self.min_samples_split and curr_depth<=self.max_depth:
            # find the best split
            best_split = self.get_best_split(dataset, num_samples, num_features)
            # check if information gain is positive
            if best_split["var_red"]>0:
                # recur left
                left_subtree = self.build_tree(best_split["dataset_left"], curr_depth+1)
                # recur right
                right_subtree = self.build_tree(best_split["dataset_right"], curr_depth+1)
                # return decision node
                return Node(best_split["feature_index"], best_split["threshold"], 
                            left_subtree, right_subtree, best_split["var_red"])
        
        # compute leaf node
        leaf_value = self.calculate_leaf_value(Y)
        # return leaf node
        return Node(value=leaf_value)
    
    def get_best_split(self, dataset, num_samples, num_features):
        ''' function to find the best split '''
        
        # dictionary to store the best split
        best_split = {}
        max_var_red = -float("inf")
        # loop over all the features
        for feature_index in range(num_features):
            feature_values = dataset[:, feature_index]
            possible_thresholds = np.unique(feature_values)
            # loop over all the feature values present in the data
            for threshold in possible_thresholds:
                # get current split
                dataset_left, dataset_right = self.split(dataset, feature_index, threshold)
                # check if childs are not null
                if len(dataset_left)>0 and len(dataset_right)>0:
                    y, left_y, right_y = dataset[:, -1], dataset_left[:, -1], dataset_right[:, -1]
                    # compute information gain
                    curr_var_red = self.variance_reduction(y, left_y, right_y)
                    # update the best split if needed
                    if curr_var_red>max_var_red:
                        best_split["feature_index"] = feature_index
                        best_split["threshold"] = threshold
                        best_split["dataset_left"] = dataset_left
                        best_split["dataset_right"] = dataset_right
                        best_split["var_red"] = curr_var_red
                        max_var_red = curr_var_red
                        
        # return best split
        return best_split
    
    def split(self, dataset, feature_index, threshold):
        ''' function to split the data '''
        
        dataset_left = np.array([row for row in dataset if row[feature_index]<=threshold])
        dataset_right = np.array([row for row in dataset if row[feature_index]>threshold])
        return dataset_left, dataset_right
    
    def variance_reduction(self, parent, l_child, r_child):
        ''' function to compute variance reduction '''
        
        weight_l = len(l_child) / len(parent)
        weight_r = len(r_child) / len(parent)
        reduction = np.var(parent) - (weight_l * np.var(l_child) + weight_r * np.var(r_child))
        return reduction
    
    def calculate_leaf_value(self, Y):
        ''' function to compute leaf node '''
        
        val = np.mean(Y)
        return val
                
    def print_tree(self, tree=None, indent=" "):
        ''' function to print the tree '''
        
        if not tree:
            tree = self.root

        if tree.value is not None:
            print(tree.value)

        else:
            print("X_"+str(tree.feature_index), "<=", tree.threshold, "?", tree.var_red)
            print("%sleft:" % (indent), end="")
            self.print_tree(tree.left, indent + indent)
            print("%sright:" % (indent), end="")
            self.print_tree(tree.right, indent + indent)
    
    def fit(self, X, Y):
        ''' function to train the tree '''
        
        dataset = np.concatenate((X, Y), axis=1)
        self.root = self.build_tree(dataset)
        
    def make_prediction(self, x, tree):
        ''' function to predict new dataset '''
        
        if tree.value!=None: return tree.value
        feature_val = x[tree.feature_index]
        if feature_val<=tree.threshold:
            return self.make_prediction(x, tree.left)
        else:
            return self.make_prediction(x, tree.right)
    
    def predict(self, X):
        ''' function to predict a single data point '''
        
        preditions = [self.make_prediction(x, self.root) for x in X]
        return preditions
    
    def mse(self, y_true, y_pred):
        return np.mean((y_true - y_pred) ** 2)
    

    def r_squared(self, y_true, y_pred):
        y_mean = np.mean(y_true)
        ss_tot = np.sum((y_true - y_mean) ** 2)
        ss_res = np.sum((y_true - y_pred) ** 2)
        r2 = 1 - (ss_res / ss_tot)
        return r2

# MODEL BUILDING

In [40]:
regressor = DecisionTreeRegressor(min_samples_split=3, max_depth=3)
regressor.fit(X_train,Y_train)
regressor.print_tree()

KeyError: 'var_red'

In [ ]:
y_pred = regressor.predict(X_test)

In [ ]:
y_pred

In [ ]:
regressor.mse(Y_test,y_pred)

In [ ]:
regressor.r_squared(Y_test,y_pred)

In [ ]:
y_pred1 = regressor.predict(X_train)

In [ ]:
regressor.r_squared(Y_train,y_pred1)

In [ ]:
from itertools import product


class GridSearchCV:
    
    def __init__(self, param_grid, cv=5):
        self.estimator = DecisionTreeRegressor(3,3)
        self.param_grid = param_grid
        self.cv = cv
        self.best_params_ = None
        self.best_score_ = None
        self.cv_results_ = []
        
    def fit(self, X, y):
        # Generate all possible combinations of hyperparameters
        hyperparams = list(product(self.param_grid.values()))
        
        # Initialize variables to store best score and hyperparameters
        best_score = -float('inf')
        best_params = None
        
        # Iterate over all combinations of hyperparameters
        for params in hyperparams:
            # Initialize estimator with the given hyperparameters
            estimator = self.estimator(params)
            
            # Run cross validation and calculate mean score
            scores = self.cross_validate(estimator, X, y, cv=self.cv)
            mean_score = np.mean(scores)
            
            # Save the results of the cross-validation
            self.cv_results_.append({'params': params, 'mean_test_score': mean_score, 'test_scores': scores})
            
            # Update best score and hyperparameters if a better score is found
            if mean_score > best_score:
                best_score = mean_score
                best_params = params
                
        # Save the best hyperparameters and score
        self.best_params_ = dict(zip(self.param_grid.keys(), best_params))
        self.best_score_ = best_score
        
        # Fit the estimator with the best hyperparameters on the full dataset
        self.estimator_ = self.estimator(best_params)
        self.estimator_.fit(X, y)
        
    def cross_validate(self, estimator, X, y, cv):
        # Split the data into k folds
        indices = np.arange(len(X))
        np.random.shuffle(indices)
        folds = np.array_split(indices, cv)
        
        scores = []
        for i in range(cv):
            # Get the training and validation sets
            train_indices = np.concatenate(folds[:i] + folds[i+1:])
            val_indices = folds[i]
            X_train, y_train = X[train_indices], y[train_indices]
            X_val, y_val = X[val_indices], y[val_indices]
            
            # Fit the estimator on the training set and predict on the validation set
            estimator.fit(X_train, y_train)
            y_pred = estimator.predict(X_val)
            
            # Calculate the score and add it to the list of scores
            score = mse(y_val, y_pred)
            scores.append(score)
            
        return scores

In [ ]:
model=GridSearchCV(param_grid)

In [ ]:
model.fit(X_train,Y_train)

# FROM SKLEARN LIBRARY

In [ ]:
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.tree import DecisionTreeRegressor
from sklearn.metrics import mean_squared_error,r2_score

In [ ]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=42)

In [ ]:
dtr= DecisionTreeRegressor(max_depth=10,random_state=42)
dtr.fit(x_train,y_train)

In [ ]:
y_pred = dtr.predict(x_test)

In [ ]:
mean_squared_error(y_test, y_pred)

In [ ]:
r2 = r2_score(y_test, y_pred)
print("R2 score:", r2)

In [ ]:
y_train_pred = dtr.predict(x_train)
r2_train = r2_score(y_train, y_train_pred)

print('Training R2 score:', r2_train)